### ISSUE TITLE
[Question] About Kubernetes version change[1.21 -> 1.28]

### ISSUE THREAD

**Issue by yak1ra** [CrowdStrike/cloud-pov#12]
kubernets 1.21 is not supported and I would like to change the version to 1.28 to be installed

So, I have changed the version of eksControlPlane.yaml.
Version: '1.21' --> Version: '1.28'

There is a release version listed in eksNodeGroup.yaml, could you tell me what to put in it?
ReleaseVersion: 1.21.12-20220523  -->  ?

**Comment by ryanjpayne** [comment]
Thanks @yak1ra this has been addressed with the latest PR.  The version is now omitted so the "Default" kubernetes version will be used (typically N-1)
